/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.hostexpanse2.gui;


import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author cristian
 */
public class LoginEmpleado extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    
    public LoginEmpleado() {
        
        
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblimageEmpleado = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        lblContrasenaEmpleado = new javax.swing.JLabel();
        lblTituloEmpleado = new javax.swing.JLabel();
        lblUsuarioEmpleado = new javax.swing.JLabel();
        txtUsuarioEmpleado = new javax.swing.JTextField();
        btnRecuperarConstasenaEmpleado = new javax.swing.JButton();
        btnIngresarEmpleado = new javax.swing.JButton();
        btnRegistrarEmpleado = new javax.swing.JButton();
        txtContrasenaEmpleado = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(254, 250, 247));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(181, 221, 212));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblimageEmpleado.setIcon(new javax.swing.ImageIcon("C:\\Users\\crist\\Documents\\NetBeansProjects\\hostExpanse\\src\\main\\java\\imagenes\\summerSfondo220px.png")); // NOI18N
        jPanel2.add(lblimageEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 230, 180));

        btnVolver.setBackground(new java.awt.Color(181, 221, 212));
        btnVolver.setIcon(new javax.swing.ImageIcon("C:\\Users\\crist\\Documents\\NetBeansProjects\\hostExpanse\\src\\main\\java\\imagenes\\flechaAtras.png")); // NOI18N
        btnVolver.setBorder(null);
        btnVolver.setBorderPainted(false);
        btnVolver.setPreferredSize(new java.awt.Dimension(80, 72));
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jPanel2.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 24, 24));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 340));

        lblContrasenaEmpleado.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        lblContrasenaEmpleado.setForeground(new java.awt.Color(0, 0, 0));
        lblContrasenaEmpleado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblContrasenaEmpleado.setText("Contraseña");
        jPanel1.add(lblContrasenaEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, 120, 20));

        lblTituloEmpleado.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        lblTituloEmpleado.setForeground(new java.awt.Color(0, 0, 0));
        lblTituloEmpleado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloEmpleado.setText("Inicio de Sesión");
        jPanel1.add(lblTituloEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 120, 20));

        lblUsuarioEmpleado.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        lblUsuarioEmpleado.setForeground(new java.awt.Color(0, 0, 0));
        lblUsuarioEmpleado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsuarioEmpleado.setText("Usuario");
        jPanel1.add(lblUsuarioEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, 120, 20));

        txtUsuarioEmpleado.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        txtUsuarioEmpleado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUsuarioEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioEmpleadoActionPerformed(evt);
            }
        });
        jPanel1.add(txtUsuarioEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, 100, -1));

        btnRecuperarConstasenaEmpleado.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        btnRecuperarConstasenaEmpleado.setText("Recuperar Contraseña");
        jPanel1.add(btnRecuperarConstasenaEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, -1, -1));

        btnIngresarEmpleado.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        btnIngresarEmpleado.setText("Ingresar");
        jPanel1.add(btnIngresarEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 240, 100, -1));

        btnRegistrarEmpleado.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        btnRegistrarEmpleado.setText("Registrar");
        btnRegistrarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarEmpleadoActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrarEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 240, 100, -1));

        txtContrasenaEmpleado.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        txtContrasenaEmpleado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtContrasenaEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, 100, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioEmpleadoActionPerformed

    private void btnRegistrarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarEmpleadoActionPerformed

        JOptionPane.showMessageDialog(null, "No puedes registrar usuarios.\nContacta con el administrador.", 
                "Warning", JOptionPane.WARNING_MESSAGE);
        
    }//GEN-LAST:event_btnRegistrarEmpleadoActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // Obtiene la pestaña actual
        Bienvenido bienvenido = new Bienvenido();
        dispose();
        bienvenido.setVisible(true);
        bienvenido.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginEmpleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresarEmpleado;
    private javax.swing.JButton btnRecuperarConstasenaEmpleado;
    private javax.swing.JButton btnRegistrarEmpleado;
    private javax.swing.JButton btnVolver;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblContrasenaEmpleado;
    private javax.swing.JLabel lblTituloEmpleado;
    private javax.swing.JLabel lblUsuarioEmpleado;
    private javax.swing.JLabel lblimageEmpleado;
    private javax.swing.JPasswordField txtContrasenaEmpleado;
    private javax.swing.JTextField txtUsuarioEmpleado;
    // End of variables declaration//GEN-END:variables

    

}
